name: Build

on:
  push:
    branches: [master]
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile:
    name: Compilation
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project_dirs: [buildimage, libbi, non-preemptive-kernel]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Compile
        run: make
        working-directory: ${{matrix.project_dirs}}
